CREATE TABLE [dbo].[Users_2025] (
	id SMALLINT IDENTITY(1,1) PRIMARY KEY,
    [name] NVARCHAR(50) UNIQUE NOT NULL,
	email NVARCHAR(255) UNIQUE NOT NULL,
	[password] NVARCHAR(255) NOT NULL,
    active BIT NOT NULL DEFAULT 0,
	deletedAt DATE NULL
);